<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\TreeRenderer\ItemRenderer;

/**
 * @var $block ItemRenderer
 * phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
 */
$item = $block->getItem();
?>
<li class="item">
    <a href="<?=$block->getCategoryUrl($item)?>">
        <?=$block->getItemPrefix()?>
        <?=$escaper->escapeHtml($item->getLabel())?>
        <?=$block->getItemPostfix()?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count">
                <?=htmlentities($item->getCount())?>
                <span class="filter-count-label">
                    <?php if ($item->getCount() == 1):?>
                        <?=__('item')?>
                    <?php else:?>
                        <?=__('items')?>
                    <?php endif;?>
                </span>
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($item->getChildren() as $child): ?>
                <?=$block->renderTreeItem($child)?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
