<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Tweakwise\Magento2Tweakwise\Model\NavigationConfig;
use Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics;

/** @var $block Template */
/** @var $escaper Escaper */

/** @var PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
$analyticsTypes = $block->getData('analyticsTypes');
$eventsData = $viewModel->getEventsData($analyticsTypes);

/** @var NavigationConfig $tweakwiseNavigationConfig */
$tweakwiseNavigationConfig = $block->getData('tweakwise_navigation_config');
$jsFormConfig = $tweakwiseNavigationConfig ? json_decode($tweakwiseNavigationConfig->getJsFormConfig()) : [];
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Tweakwise_Magento2Tweakwise/js/analytics": {
                "eventsData": <?= $eventsData ?>,
                "bindItemClickEventsConfig": {
                    "productListSelector": "<?= $escaper->escapeHtmlAttr($jsFormConfig->tweakwiseNavigationForm->productListSelector ?? ''); ?>",
                    "productSelector": "<?= $escaper->escapeHtmlAttr($jsFormConfig->tweakwiseNavigationForm->productSelector ?? ''); ?>",
                    "analyticsEndpoint": "<?= /* @noEscape */ $jsFormConfig->tweakwiseNavigationForm->analyticsEndpoint ?? ''; ?>",
                    "twRequestId": "<?= $escaper->escapeHtmlAttr($jsFormConfig->tweakwiseNavigationForm->twRequestId ?? ''); ?>"
                }
            }
        }
    }
</script>
<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_Magento2Tweakwise::js/analytics.js')); ?>"></script>
