<?php

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
$analyticsType = $block->getData('analyticsType');
$value = $analyticsType === 'product' ? $viewModel->getProductKey() : $viewModel->getSearchQuery();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Tweakwise_Magento2Tweakwise/js/analytics": {
              "value": "<?= $escaper->escapeHtmlAttr($value); ?>",
              "type": "<?= $escaper->escapeHtmlAttr($analyticsType); ?>",
        }
    }
}
</script>
<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_Magento2Tweakwise::js/analytics.js')); ?>"></script>
