<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var $block \Tweakwise\Magento2Tweakwise\Block\Autocomplete\FormMini
 * @var $escaper Escaper
 * phpcs:disable Magento2.Legacy.PhtmlTemplate.TextJavascriptTypeFound
 */

use Magento\Framework\Escaper;

?>
<script
    id="autocomplete-item-template"
    type="text/x-magento-template"
    data-url="<?=$escaper->escapeUrl($block->getAjaxUrl() . 'blocks/1')?>">
    <% if (typeof data.block !== 'undefined' && data.block.nrofitems > 0) { %>
        <li class="<%- data.row_class %> qs-suggestion-heading" id="qs-option-<%- data.index %>" role="option">
            <span class="qs-option-name"><%= data.block.name %></span>
        </li>

        <% var items = (data.block.items.item && Array.isArray(data.block.items.item) && data.block.items.item[0]) ? data.block.items.item : data.block.items; %>
        <% _.each(items, function (item, index) { %>
            <% if (item && item.type === 'product') { %>
                <li
                    class="<%- item.row_class %> product-item"
                    id="qs-option-<%- data.index %>-<%- index %>"
                    data-url="<%- item.url %>"
                    role="option">
                    <% if (item.image) { %>
                        <img class="qs-option-image" src="<%- item.image %>" alt="<%- item.title %>">
                    <% } %>

                    <div class="qs-option-info-container">
                        <span class="qs-option-name"><%= item.title %></span>

                        <div class="price-box">
                            <% if (Math.abs(item.final_price - item.price) < 0.0001) { %>
                                <span class="price-container">
                                    <span class="price-wrapper">
                                        <span class="price"><%= autocompleteFormatPrice(item.price) %></span>
                                    </span>
                                </span>
                            <% } else { %>
                                <span class="special-price">
                                    <span class="price-container">
                                        <span class="price-label"><?=$escaper->escapeHtml(__('Special Price'))?></span>
                                        <span class="price-wrapper">
                                            <span class="price"><%= autocompleteFormatPrice(item.final_price) %></span>
                                        </span>
                                    </span>
                                </span>

                                <span class="old-price sly-old-price">
                                    <span class="price-container">
                                        <span class="price-label"><?=$escaper->escapeHtml(__('Regular Price'))?></span>
                                        <span class="price-wrapper">
                                            <span class="price"><%= autocompleteFormatPrice(item.price) %></span>
                                        </span>
                                    </span>
                                </span>
                            <% } %>
                        </div>
                    </div>
                </li>
            <% } else { %>
                <li
                    class="<%- item.row_class %> visual-item"
                    id="qs-option-<%- data.index %>-<%- index %>"
                    role="option">
                    <% if (item.image) { %>
                        <img class="qs-option-image" src="<%- item.image %>" alt="<%- item.title %>">
                    <% } %>

                    <div class="qs-option-info-container">
                        <span class="qs-option-name"><%= item.title %></span>
                    </div>
                </li>
            <% } %>
        <% }); %>
    <% } else if (data.type === 'suggestion') { %>
        <li class="<%- data.row_class %>" id="qs-option-<%- data.index %>" role="option">
            <span class="qs-option-name"><%= data.title %></span>
            <span aria-hidden="true" class="amount"><%- data.num_results %></span>
        </li>
    <% } else if (data.type === 'suggestion_group') { %>
        <li class="<%- data.row_class %> qs-suggestion-heading" id="qs-option-<%- data.index %>" role="option">
            <span class="qs-option-name"><%= data.title %></span>
            <span aria-hidden="true" class="amount"><%- data.num_results %></span>
        </li>
        <% _.each (data.suggestions, function (suggestion, index) { %>
            <li class="<%- suggestion.row_class %> qs-suggestion-item"
                id="qs-option-<%- data.index %>-<%- index %>"
                <% if (suggestion.url) { %>
                    data-url="<%- suggestion.url %>"
                <% } %>
                role="option"
            >
                <span class="qs-option-name"><%= suggestion.title %></span>
            </li>
        <% }); %>
    <% } %>
</script>
<script type="text/javascript">
    require(['Magento_Catalog/js/price-utils'], function(priceUtils){
        window['autocompleteFormatPrice'] = function(price) {
            return priceUtils.formatPrice(price, <?= /* @noEscape */($block->getJsonPriceFormat())?>);
        };
    });
</script>
