<?php

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */

$searchQuery = $block->getSearchQuery();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Tweakwise_Magento2Tweakwise/js/search-page": {
              "instanceKey": "<?= $escaper->escapeHtmlAttr($instanceKey); ?>"
        }
    }
}
</script>
<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_Magento2Tweakwise::js/search-page.js')); ?>"></script>
