include:
  - project: 'ci-cd/semantic-release'
    ref: main
    file: 'semantic-release.yml'

  - project: 'ci-cd/magento-module'
    ref: master
    file: 'codeception-ci.yml'

  - project: 'ci-cd/magento-module'
    ref: master
    file: 'codequality-ci.yml'

  - project: 'ci-cd/tweakwise'
    ref: main
    file: 'github-release.yml'

  - project: 'ci-cd/tweakwise'
    ref: main
    file: 'demo-pipeline-trigger.yml'
variables:
  MAGENTO_PHP_VERSION: '8.2'

magento-module/test/functional:
  variables:
    MIN_PHP_VERSION: '8.2'
    DISABLE_DEPENDENCY_AUDIT: "true"
    CODECEPTION_ARGS: '-vvv'
  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "failed" ] && [ -x ./vendor/bin/codecept ]; then
        ./vendor/bin/codecept run --xml --html --steps -vvv --debug --fail-fast=0 || true
      fi

release:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
