<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
$tweakwiseCookieName = $block->getCookieName();
$apiUrl = $block->getApiUrl();
$productKey = $block->getProductKey();
$instanceKey = $block->getInstanceKey();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Tweakwise_Magento2Tweakwise/js/product-page": {
                "apiUrl": "<?= $apiUrl; ?>pageview",
            "tweakwiseCookieName": "<?= $tweakwiseCookieName; ?>",
            "productKey": "<?= $productKey; ?>",
            "instanceKey": "<?= $instanceKey; ?>"
        }
    }
}
</script>
<script src="<?= $this->getViewFileUrl('Tweakwise_Magento2Tweakwise::js/product-page.js'); ?>"></script>
