<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\LinkRenderer\ItemRenderer;

/**
 * @var $block ItemRenderer
 * @var $escaper Escaper
 */
$item = $block->getItem();
$hasHiddenItems = $block->hasHiddenItems();
$hasAlternateSortOrder = $block->hasAlternateSortOrder();
?>
<li class="item<?=$block->itemDefaultHidden($item) ? ' default-hidden' : ''?>"
    <?php if ($hasHiddenItems && $hasAlternateSortOrder):?>
        data-alternate-sort="<?= $escaper->escapeHtmlAttr($item->getAlternateSortOrder());?>"
    <?php endif;?>
>
    <a href="<?=$escaper->escapeUrl($block->getCategoryUrl($item))?>">
        <?=$escaper->escapeHtmlAttr($block->getItemPrefix())?>
        <?=$escaper->escapeHtml($item->getLabel())?>
        <?=$escaper->escapeHtmlAttr($block->getItemPostfix())?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count">
                <?=$escaper->escapeHtml($item->getCount())?>
                <span class="filter-count-label">
                    <?php if ($item->getCount() == 1):?>
                        <?=$escaper->escapeHtml(__('item'))?>
                    <?php else:?>
                        <?=$escaper->escapeHtml(__('items'))?>
                    <?php endif;?>
                </span>
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($block->getChildren() as $child): ?>
                <?= /* @noEscape */$block->renderLinkItem($child)?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
