<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\LinkRenderer\ItemRenderer;

/**
 * @var $block ItemRenderer
 */
$item = $block->getItem();
$hasHiddenItems = $block->hasHiddenItems();
$hasAlternateSortOrder = $block->hasAlternateSortOrder();
?>
<li class="item<?=$block->itemDefaultHidden($item) ? ' default-hidden' : ''?>"
    <?php if ($hasHiddenItems && $hasAlternateSortOrder):?>
        data-alternate-sort="<?=$item->getAlternateSortOrder();?>"
    <?php endif;?>
>
    <a href="<?=$block->getCategoryUrl($item)?>">
        <?=$block->getItemPrefix()?>
        <?=$escaper->escapeHtml($item->getLabel())?>
        <?=$block->getItemPostfix()?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count">
                <?=htmlentities($item->getCount())?>
                <span class="filter-count-label">
                    <?php if ($item->getCount() == 1):?>
                        <?=__('item')?>
                    <?php else:?>
                        <?=__('items')?>
                    <?php endif;?>
                </span>
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($block->getChildren() as $child): ?>
                <?=$block->renderLinkItem($child)?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
