<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\SwatchRenderer */
/** @var $escaper Escaper */

use Magento\Framework\Escaper;

$hasHiddenItems = $block->hasHiddenItems();

?>
<?php $swatchData = $block->getSwatchData(); ?>
<div class="swatch-attribute swatch-layered <?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     attribute-code="<?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     attribute-id="<?= $escaper->escapeHtmlAttr($swatchData['attribute_id']) ?>"
     data-mage-init='{"tweakwiseNavigationSort":[]}'>
    <?php if ($block->isSearchable()): ?>
        <input tabindex="-1" data-max-visible="<?= $escaper->escapeHtmlAttr($block->getMaxItemsShown())?>" type="text" class="tw_filtersearch js-skip-submit" name="tw_filtersearch" placeholder="<?= $escaper->escapeHtmlAttr($block->getSearchPlaceholder()); ?>" >
        <div style="display: none" class="search_no_results"><?= $escaper->escapeHtmlAttr($block->getSearchNoResultsText()); ?></div>
    <?php endif; ?>
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <?php $item = $block->getItemForSwatch($option);?>
            <?php if (!$item) continue; ?>
            <a <?= /* @noEscape */ $block->renderAnchorHtmlTagAttributes($item);?>
                tabindex="0"
                role="button"
                aria-labelledby="<?= $escaper->escapeHtmlAttr($item->getFilter()->getUrlKey()) ?> <?= $escaper->escapeHtmlAttr($item->getCssId()) ?>"
                class="swatch-option-link-layered <?php /* @noEscape */ if ($block->shouldDisplayProductCountOnLayer()): ?>swatch-with-count<?php endif; ?><?= /* @noEscape */ $block->itemDefaultHidden($item) ? ' default-hidden' : ''?>"
            >
                <?php $cssId = $item->getCssId();?>
                <input id="<?=$escaper->escapeHtmlAttr($cssId)?>" style="display: none"
                       name="<?= $escaper->escapeHtmlAttr($item->getFilter()->getFacet()->getFacetSettings()->getUrlKey())?>[]"
                       type="checkbox" <?=/* @noEscape */ ($item->isSelected() ? 'checked="checked"' : '')?>
                       value="<?=$escaper->escapeHtmlAttr($item->getLabel())?>"
                >
                <label aria-label="<?= $escaper->escapeHtmlAttr($label['label']); ?>" for="<?= $escaper->escapeHtmlAttr($cssId) ?>">
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?= $escaper->escapeHtmlAttr($label['custom_style']) ?>"
                                 tabindex="-1"
                                 option-type="3"
                                 option-id="<?= $escaper->escapeHtmlAttr($option) ?>"
                                 option-label="<?=  $escaper->escapeHtmlAttr($label['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ></div>
                            <?php    break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="swatch-option image <?= $escaper->escapeHtmlAttr($label['custom_style']) ?>"
                                 tabindex="-1"
                                 option-type="2"
                                 option-id="<?= $escaper->escapeHtmlAttr($option) ?>"
                                 option-label="<?= $escaper->escapeHtmlAttr($label['label']) ?>"
                                 option-tooltip-thumb="<?= $escaper->escapeHtmlAttr($swatchThumbPath) ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?= $escaper->escapeHtmlAttr($swatchImagePath) ?>) no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '1':
                            ?>
                            <div class="swatch-option color <?= $escaper->escapeHtmlAttr($label['custom_style']) ?>"
                                 tabindex="-1"
                                 option-type="1"
                                 option-id="<?= $escaper->escapeHtmlAttr($option) ?>"
                                 option-label="<?= $escaper->escapeHtmlAttr($label['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?= $escaper->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?>"
                                 style="background: <?= $escaper->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?> no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '0':
                        default:
                            ?>
                            <div class="swatch-option text <?= $escaper->escapeHtmlAttr($label['custom_style']) ?>"
                                 tabindex="-1"
                                 option-type="0"
                                 option-id="<?=  $escaper->escapeHtmlAttr($option) ?>"
                                 option-label="<?= $escaper->escapeHtmlAttr($label['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ><?= $escaper->escapeHtml($swatchData['swatches'][$option]['value']) ?></div>
                            <?php    break;
                    } ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count">
                            <?= (int)$item->getCount()?>
                            <span class="filter-count-label">
                                <?php if ($item->getCount() == 1):?>
                                    <?=__('item')?>
                                <?php else:?>
                                    <?=__('items')?>
                                <?php endif;?>
                            </span>
                        </span>
                    <?php endif; ?>
                <?php } ?>
                </label>
            </a>
        <?php endforeach; ?>
    </div>

    <?php if ($hasHiddenItems): ?>
        <a class="more-items"><?=$escaper->escapeHtml(__($block->getMoreItemText()))?></a>
        <a class="less-items default-hidden"><?=$escaper->escapeHtml(__($block->getLessItemText()))?></a>
    <?php endif; ?>
</div>

<script>
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?=  $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
