<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\TreeRenderer;

/** @var $block \Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\LinkRenderer */
$hasHiddenItems = $block->hasHiddenItems();
?>
<div data-mage-init='<?=$block->getJsSortConfig()?>'>
    <ol class="items link-attribute">
        <?php foreach ($block->getItems() as $item): ?>
            <?=$block->renderLinkItem($item)?>
        <?php endforeach; ?>
    </ol>

    <?php if ($hasHiddenItems): ?>
        <a class="more-items"><?=__($block->getMoreItemText())?></a>
        <a class="less-items default-hidden"><?=__($block->getLessItemText())?></a>
    <?php endif; ?>
</div>

