<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\SliderRenderer;

/**
 * @var $block SliderRenderer
 * @var $escaper Escaper
 */
$itemPrefix = $block->getItemPrefix();
$itemPostfix = $block->getItemPostfix();
$urlKey = $block->getUrlKey();
$minValue = $block->getMinValue();
$maxValue = $block->getMaxValue();
$totalRange = $block->getTotalRange();
$currentMinValue = $block->getCurrentMinValue();
$currentMaxValue = $block->getCurrentMaxValue();
$sliderUrlInputValue = sprintf('%s-%s', $currentMinValue, $currentMaxValue);
$disabledSliderUrlInputValue = sprintf('%s-%s', $minValue, $maxValue);
$cointainsBuckets = $block->containsBuckets();
$cointainsClickpoints = $block->containsClickpoints();
$clickpointCounter = 0;
?>
<div class="slider-attribute" id="attribute-slider-<?=$escaper->escapeHtmlAttr($block->getCssId())?>">
    <?php
    if ($cointainsBuckets): ?>
        <div class="buckets">
            <?php
            $bucketHightFactor = $block->getBucketHightFactor();
            ?>
            <?php foreach ($block->getBuckets() as $bucket): ?>
                <?php
                $rangeMin = floor($bucket['rangemin']);
                $rangeMax = ceil($bucket['rangemax']);
                $bucketHeight = floor($bucket['relativeamount'] * $bucketHightFactor);
                $bucketWidth = (($rangeMax - $rangeMin) / $totalRange) * 100;
                ?>
                <a href="javascript:void(0);" class="bucket-link" style="width: <?= $escaper->escapeHtmlAttr($bucketWidth) ?>%" data-rangemin="<?= $escaper->escapeHtmlAttr($rangeMin) ?>" data-rangemax="<?= $escaper->escapeHtmlAttr($rangeMax) ?>">
                    <div class="bucket-range" style="height: <?= $escaper->escapeHtmlAttr($bucketHeight) ?>px;">
                    </div>
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($cointainsClickpoints): ?>
        <?php
            $totalClickpoints = count($block->getClickpoints());
            $totalClickpointsRange = $totalRange + ($totalClickpoints * 2);
        ?>
        <div class="indicators">
            <?php foreach ($block->getClickpoints() as $clickpoint): ?>
                <?php
                $clickpointWidth = 10 * $clickpointCounter;
                $clickpointPosition = floor((($clickpoint['value'] - $minValue) / $totalClickpointsRange) * 100);
                $clickpointCounter++;
                ?>
            <a>
                <div class="indicator" style="left: <?= $escaper->escapeHtmlAttr($clickpointPosition) ?>%">
                    <div class="indicator-number"><?= $escaper->escapeHtml(ceil($clickpoint['value'])) ?></div>
                    <div class="indicator-arrow"></div>
                </div>
            </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="slider" data-mage-init="<?=$escaper->escapeHtmlAttr($block->getJsSliderConfig())?>"></div>
    <div class="labels">
        <span class="current-min-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($currentMinValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
        <span class="current-max-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($currentMaxValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
    </div>
    <div class="slider-inputs">
        <div class="slider-min-wrapper">
            <label for="<?= $escaper->escapeUrl($urlKey) ?>-min"><?= $escaper->escapeHtml(__('From'))?></label>
            <input type="text"
                   class="slider-min js-skip-submit"
                   id="<?= $escaper->escapeHtmlAttr($urlKey) ?>-min"
                   name="<?= $escaper->escapeHtmlAttr($urlKey) ?>-min"
                   value="<?= $escaper->escapeHtmlAttr($currentMinValue) ?>"
            >
        </div>
        <div class="slider-max-wrapper">
            <label for="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"><?=$escaper->escapeHtml(__('To'))?></label>
            <input type="text"
                   class="slider-max js-skip-submit"
                   id="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"
                   name="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"
                   value="<?= $escaper->escapeHtmlAttr($currentMaxValue) ?>"
            >
        </div>
        <input type="hidden"
               data-disabled-input="<?= $escaper->escapeHtmlAttr($disabledSliderUrlInputValue)?>"
               <?php if ($sliderUrlInputValue === $disabledSliderUrlInputValue):?>
               disabled="disabled"
               <?php endif;?>
               id="<?=$escaper->escapeHtmlAttr($block->getCssId())?>"
               class="slider-url-value"
               name="<?= $escaper->escapeHtmlAttr($urlKey) ?>"
               value="<?=$escaper->escapeHtmlAttr($sliderUrlInputValue)?>"
        >
    </div>
</div>

<style>
    .buckets {
        display: flex;
        align-items: flex-end; /* Align children to the bottom */
        width: calc(100% - 20px);
        margin-left: 5px;
        position: relative; /* Ensure clickpoints are positioned relative to this container */
    }

    .bucket-range {
        background-color: #f1f1f1;
        border: 1px solid #e0e0e0;
        border-radius: 1px;
        margin: 0 0px;
        display: flex;
        align-items: flex-end; /* Align the content to the bottom */
    }

    .bucket-link {
        margin: 0 1px;
        text-decoration: none !important; /* Remove underline from links */
    }

    .bucket-link:hover{
        background-color: inherit !important;
    }

    .slider-attribute {
        position: relative; /* Ensure the indicator is positioned relative to the slider-attribute container */
    }

    .indicators {
        height: 20px;
        margin-top: 5px;
        margin-bottom: 10px;
        width: calc(100% - 20px);
    }

    .indicators a:hover {
        background-color: inherit;
    }

    .indicator {
        width: 30px;
        float: left;
        position: absolute; /* Ensure the arrow is positioned relative to the indicator */
    }

    .indicator-arrow {
        width: 0;
        height: 0;
        text-align: right;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 10px solid black; /* Change to border-top to point the arrow upwards */
    }

    .indicator-number {
        text-align: left;
        font-size: 12px;
    }
</style>
