<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\SliderRenderer;

/**
 * @var $block SliderRenderer
 * @var $escaper Escaper
 */
$itemPrefix = $block->getItemPrefix();
$itemPostfix = $block->getItemPostfix();
$urlKey = $block->getUrlKey();
$minValue = $block->getMinValue();
$maxValue = $block->getMaxValue();
$currentMinValue = $block->getCurrentMinValue();
$currentMaxValue = $block->getCurrentMaxValue();
$sliderUrlInputValue = sprintf('%s-%s', $currentMinValue, $currentMaxValue);
$disabledSliderUrlInputValue = sprintf('%s-%s', $minValue, $maxValue);
?>
<div class="slider-attribute" id="attribute-slider-<?=$escaper->escapeHtmlAttr($block->getCssId())?>">
    <div class="labels">
        <span class="min-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($minValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
        <span class="max-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($maxValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
    </div>
    <div class="slider" data-mage-init="<?=$escaper->escapeHtmlAttr($block->getJsSliderConfig())?>"></div>
    <div class="labels">
        <span class="current-min-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($currentMinValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
        <span class="current-max-value">
            <span class="prefix"><?= $escaper->escapeHtml($itemPrefix) ?></span>
            <?= $escaper->escapeHtml($block->renderValue($currentMaxValue))?>
            <span class="postfix"><?= $escaper->escapeHtml($itemPostfix) ?></span>
        </span>
    </div>
    <div class="slider-inputs">
        <div class="slider-min-wrapper">
            <label for="<?= $escaper->escapeUrl($urlKey) ?>-min"><?= $escaper->escapeHtml(__('From'))?></label>
            <input type="text"
                   class="slider-min js-skip-submit"
                   id="<?= $escaper->escapeHtmlAttr($urlKey) ?>-min"
                   name="<?= $escaper->escapeHtmlAttr($urlKey) ?>-min"
                   value="<?= $escaper->escapeHtmlAttr($currentMinValue) ?>"
            >
        </div>
        <div class="slider-max-wrapper">
            <label for="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"><?=$escaper->escapeHtml(__('To'))?></label>
            <input type="text"
                   class="slider-max js-skip-submit"
                   id="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"
                   name="<?= $escaper->escapeHtmlAttr($urlKey) ?>-max"
                   value="<?= $escaper->escapeHtmlAttr($currentMaxValue) ?>"
            >
        </div>
        <input type="hidden"
               data-disabled-input="<?= $escaper->escapeHtmlAttr($disabledSliderUrlInputValue)?>"
               <?php if ($sliderUrlInputValue === $disabledSliderUrlInputValue):?>
               disabled="disabled"
               <?php endif;?>
               id="<?=$escaper->escapeHtmlAttr($block->getCssId())?>"
               class="slider-url-value"
               name="<?= $escaper->escapeHtmlAttr($urlKey) ?>"
               value="<?=$escaper->escapeHtmlAttr($sliderUrlInputValue)?>"
        >
    </div>
</div>
