<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\SwatchRenderer */
/** @var $escaper Escaper */

use Magento\Framework\Escaper;

?>
<?php $swatchData = $block->getSwatchData(); ?>
<div class="swatch-attribute swatch-layered <?=  $swatchData['attribute_code'] ?>"
     attribute-code="<?=  $swatchData['attribute_code'] ?>"
     attribute-id="<?=  $swatchData['attribute_id'] ?>"
     data-mage-init='{"tweakwiseNavigationSort":[]}'>
    <?php if ($block->isSearchable()): ?>
        <input data-max-visible="<?=  $block->getMaxItemsShown()?>" type="text" class="tw_filtersearch js-skip-submit" name="tw_filtersearch" placeholder="<?= $block->getSearchPlaceholder(); ?>" >
        <div style="display: none" class="search_no_results"><?= $block->getSearchNoResultsText(); ?></div>
    <?php endif; ?>
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <?php $item = $block->getItemForSwatch($option);?>
            <?php if (!$item) {
                continue;
            } ?>
            <a <?=$block->renderAnchorHtmlTagAttributes($item);?>
                aria-label="<?=  $label['label'] ?>"
                class="swatch-option-link-layered"
            >
                <?php $cssId = $item->getCssId();?>
                <input id="<?=$cssId?>" style="display: none"
                       name="<?=$item->getFilter()->getFacet()->getFacetSettings()->getUrlKey()?>[]"
                       type="checkbox" <?=($item->isSelected() ? 'checked="checked"' : '')?>
                       value="<?=$block->escapeHtmlAttr($item->getLabel())?>"
                >
                <label for="<?=$cssId?>">
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?=  $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="3"
                                 option-id="<?=  $option ?>"
                                 option-label="<?=  $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ></div>
                            <?php    break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="swatch-option image <?=  $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="2"
                                 option-id="<?=  $option ?>"
                                 option-label="<?=  $label['label'] ?>"
                                 option-tooltip-thumb="<?=  $swatchThumbPath ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?=  $swatchImagePath ?>) no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '1':
                            ?>
                            <div class="swatch-option color <?=  $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="1"
                                 option-id="<?=  $option ?>"
                                 option-label="<?=  $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?=  $swatchData['swatches'][$option]['value'] ?>"
                                 style="background: <?=  $swatchData['swatches'][$option]['value'] ?> no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '0':
                        default:
                            ?>
                            <div class="swatch-option text <?=  $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="0"
                                 option-id="<?=  $option ?>"
                                 option-label="<?=  $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ><?=  $swatchData['swatches'][$option]['value'] ?></div>
                            <?php    break;
                    } ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count">
                            <?=$item->getCount()?>
                            <span class="filter-count-label">
                                <?php if ($item->getCount() == 1):?>
                                    <?=__('item')?>
                                <?php else:?>
                                    <?=__('items')?>
                                <?php endif;?>
                            </span>
                        </span>
                    <?php endif; ?>
                <?php } ?>
                </label>
            </a>
        <?php endforeach; ?>
    </div>
</div>

<script>
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?=  $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
