<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Element\Template $searchBannerLayout */

$banners = $block->getProductsTopBanner();

if (!empty($banners)) {
    $searchBannerLayout = $block->getLayout()->createBlock(\Magento\Framework\View\Element\Template::class);
    $searchBannerLayout->setData(['banners' => $banners]);
    $searchBannerLayout->setTemplate("Tweakwise_Magento2Tweakwise::searchbanner/search.banner.phtml");
    echo $searchBannerLayout->toHtml();
}
