<?php

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\Action\Action;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var AbstractProduct $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

/** @var Product $product */
$_product = $block->getData('product');
if (!$_product) {
    return;
}
$parentBlock = $block->getData('parent_block');
$viewMode = $block->getData('view_mode');
$imageDisplayArea = $block->getData('image_display_area');
$pos = $block->getData('pos');
$_helper = $block->getData('output_helper');
$templateType = $block->getData('template_type');
$showDescription = $block->getData('show_description');
?>
<li class="item product product-item">
    <div class="product-item-info"
         id="product-item-info_<?=  $_product->getId() ?>"
         data-container="product-<?=  $viewMode ?>">
        <?php
        $productImage = $block->getImage($_product, $imageDisplayArea);
        if ($pos != null) {
            $position = 'left:' . $productImage->getWidth() . 'px;'
                . 'top:' . $productImage->getHeight() . 'px;';
        }
        ?>
        <?php // Product Image ?>
        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
           class="product photo product-item-photo"
           tabindex="-1">
            <?= $productImage->toHtml() ?>
        </a>
        <div class="product details product-item-details">
            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
            <strong class="product name product-item-name">
                <a class="product-item-link"
                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                    <?= $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                </a>
            </strong>
            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
            <?=  $block->getProductPrice($_product) ?>

            <?= $block->getProductDetailsHtml($_product) ?>

            <div class="product-item-inner">
                <div class="product actions product-item-actions">
                    <div class="actions-primary">
                        <?php if ($_product->isSaleable()):?>
                            <?php $postParams = $parentBlock->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form"
                                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                  data-mage-init='{"catalogAddToCart": {}}'
                                  method="post">
                                <?php $viewModel = $parentBlock->getData('viewModel'); ?>
                                <?php $options = $viewModel ? $viewModel->getOptionsData($_product) : []; ?>
                                <?php foreach ($options as $optionItem): ?>
                                    <input type="hidden"
                                           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                <?php endforeach; ?>
                                <input type="hidden"
                                       name="product"
                                       value="<?=  $postParams['data']['product'] ?>">
                                <input type="hidden"
                                       name="<?=  Action::PARAM_NAME_URL_ENCODED ?>"
                                       value="<?=
                                        $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                        ?>">
                                <?= $block->getBlockHtml('formkey') ?>
                                <button type="submit"
                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                        class="action tocart primary"
                                        disabled>
                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                </button>
                            </form>
                        <?php else:?>
                            <?php if ($_product->isAvailable()):?>
                                <div class="stock available">
                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                            <?php else:?>
                                <div class="stock unavailable">
                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                         $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                        ) : '' ?>
                    <div data-role="add-to-links" class="actions-secondary">
                        <?php if ($addToBlock = $parentBlock->getChildBlock('addto')): ?>
                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                        <?php endif; ?>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                         $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                        ) : '' ?>
                </div>
                <?php if ($showDescription): ?>
                    <div class="product description product-item-description">
                        <?=  $_helper->productAttribute(
                            $_product,
                            $_product->getShortDescription(),
                            'short_description'
                        ) ?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           title="<?=  $_productNameStripped ?>"
                           class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
         $secureRenderer->renderStyleAsTag(
            $position,
            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
        ) : '' ?>
</li>
