<?php

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\ActionInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var AbstractProduct $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

/** @var Product $product */
$_item = $block->getData('item');
if (!$_item) {
    return;
}
$type = $block->getData('type');
$image = $block->getData('image');
$templateType = $block->getData('template_type');
$canItemsAddToCart = $block->getData('can_items_add_to_cart');
$showAddTo = $block->getData('show_add_to');
$showCart = $block->getData('show_cart');
$parentBlock = $block->getData('parent_block');
?>
<?php $available = ''; ?>
<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
    <?php if (!$_item->getRequiredOptions()):?>
        <?php $available = 'related-available'; ?>
    <?php endif; ?>
<?php endif; ?>
<?php if ($type == 'related' || $type == 'upsell'):?>
    <li class="item product product-item"
    id="product-item_<?= /* @noEscape */ $_item->getId() ?>"
    data-shuffle-group="<?= $parentBlock->escapeHtmlAttr($_item->getPriority()) ?>" >
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        'display:none;',
        'li#product-item_' . $_item->getId()
    ) ?>
<?php else:?>
    <li class="item product product-item">
<?php endif; ?>
<div class="product-item-info <?= /* @noEscape */ $available ?>">
    <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
    <a href="<?= $parentBlock->escapeUrl($parentBlock->getProductUrl($_item)) ?>"
       class="product photo product-item-photo">
        <?= $parentBlock->getImage($_item, $image)->toHtml() ?>
    </a>
    <div class="product details product-item-details">
        <strong class="product name product-item-name"><a
                class="product-item-link"
                title="<?= $parentBlock->escapeHtmlAttr($_item->getName()) ?>"
                href="<?= $parentBlock->escapeUrl($parentBlock->getProductUrl($_item)) ?>">
                <?= $parentBlock->escapeHtml($_item->getName()) ?></a>
        </strong>

        <?= /* @noEscape */ $parentBlock->getProductPrice($_item) ?>

        <?php if ($templateType):?>
            <?= $parentBlock->getReviewsSummaryHtml($_item, $templateType) ?>
        <?php endif; ?>

        <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
            && $type == 'related'):?>
            <?php if (!$_item->getRequiredOptions()):?>
                <div class="field choice related">
                    <input
                        type="checkbox"
                        class="checkbox related"
                        id="related-checkbox<?= $parentBlock->escapeHtmlAttr($_item->getId()) ?>"
                        name="related_products[]"
                        value="<?= $parentBlock->escapeHtmlAttr($_item->getId()) ?>" />
                    <label class="label"
                           for="related-checkbox<?= $parentBlock->escapeHtmlAttr($_item->getId())
                           ?>"><span><?= $parentBlock->escapeHtml(__('Add to Cart')) ?></span>
                    </label>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($showAddTo || $showCart):?>
            <?php // phpcs:disable ?>
            <div class="product actions product-item-actions">
                <?php if ($showCart):?>
                    <div class="actions-primary">
                        <?php if ($_item->isSaleable()):?>
                            <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                <button
                                    class="action tocart primary"
                                    data-mage-init='{"redirectUrl": {"url": "<?= $parentBlock->escapeUrl($parentBlock->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $parentBlock->escapeHtmlAttr(__('Add to Cart')) ?>">
                                    <span><?= $parentBlock->escapeHtml(__('Add to Cart')) ?></span>
                                </button>
                            <?php else :?>
                                <?php
                                /** @var $viewModel PreparePostData */
                                $viewModel = $parentBlock->getViewModel();
                                $postArray = $viewModel->getPostData(
                                    $parentBlock->escapeUrl($parentBlock->getAddToCartUrl($_item)),
                                    ['product' => $_item->getEntityId()]
                                );
                                $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                ?>
                                <form data-role="tocart-form"
                                      data-product-sku="<?= $parentBlock->escapeHtmlAttr($_item->getSku()) ?>"
                                      action="<?= $parentBlock->escapeUrl($parentBlock->getAddToCartUrl($_item)) ?>"
                                      method="post">
                                    <input type="hidden" name="product"
                                           value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                    <input type="hidden"
                                           name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                           value="<?= /* @noEscape */ $value ?>">
                                    <?= $parentBlock->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="<?= $parentBlock->escapeHtmlAttr(__('Add to Cart')) ?>"
                                            class="action tocart primary">
                                        <span><?= $parentBlock->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                </form>
                            <?php endif; ?>
                        <?php else:?>
                            <?php if ($_item->isAvailable()):?>
                                <div class="stock available">
                                    <span><?= $parentBlock->escapeHtml(__('In stock')) ?></span>
                                </div>
                            <?php else:?>
                                <div class="stock unavailable">
                                    <span><?= $parentBlock->escapeHtml(__('Out of stock')) ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

                <?php if ($showAddTo):?>
                    <div class="secondary-addto-links actions-secondary"
                         data-role="add-to-links">
                        <?php if ($addToBlock = $parentBlock->getChildBlock('addto')):?>
                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php // phpcs:enable ?>
        <?php endif; ?>
    </div>
</div>
</li>
