<?php

use Magento\Framework\Escaper;

/** @var array $banners  */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

$banners = $block->getData('banners');
$styling = ($banners[0]['location'] == 'ContainerTop') ? 'margin-right: auto; margin-left: auto;' : '';
?>
<div class="searchbanners" style="<?= $escaper->escapeHtmlAttr($styling) ?>">
    <?php foreach ($banners as $banner): ?>
        <?php if (!empty($banner['clickurl'])): ?>
            <a href="<?= $escaper->escapeUrl($banner['clickurl']); ?>" type="<?= $escaper->escapeHtmlAttr($banner['clicktarget']); ?>">
        <?php endif; ?>
        <img class="searchbanner <?= $escaper->escapeHtmlAttr(strtolower($banner['type'])); ?>" src="<?= $escaper->escapeUrl($banner['imageurl']); ?>">
        <?php if (!empty($banner['clickurl'])): ?>
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

<style>
    .mobile {
        display: none;
    }

    .searchbanners {
        max-width: 1536px;
    }

    .searchbanner {
        width: 100%;
    }

    @media only screen and (max-width: 768px) {
        .searchbanner.desktop {
            display: none;
        }

        .searchbanner.mobile {
            display: block;
        }
    }
</style>
